# Generated by Django 5.0.4 on 2024-04-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_is_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_discount',
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.CharField(choices=[('Activ', 'activ'), ('Inactive', 'inactive')], max_length=8),
        ),
    ]
