# Generated by Django 5.0.4 on 2024-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.CharField(choices=[('Publish', 'publish'), ('Nopublish', 'nopublish')], default='Nopublish', max_length=9),
        ),
    ]
